### PR TITLE
Enable grouping for dependabot

### PR DESCRIPTION
**Pull request by inteon**
This PR adds grouping options for dependabot, it will make dependabot create single grouped PRs to upgrade deps.

https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups

see https://github.com/cert-manager/issuer-lib/pull/65 & https://github.com/cert-manager/issuer-lib/pull/67 for working example

### CODE REVIEW

**Review by erikgb — COMMENTED** [review]
Do we really want to group **everything**? I think the cert-manager dependency will control most of the "problematic" dependencies. Could it be an option to ignore k8s dependencies (including controller-runtime) in Dependabot configuration?

**Comment by inteon** [comment]
> Do we really want to group **everything**? I think the cert-manager dependency will control most of the "problematic" dependencies. Could it be an option to ignore k8s dependencies (including controller-runtime) in Dependabot configuration?

I think it is the easiest solution right now:
1. similarly to how I upgrade dependencies, it upgrades everything at the same time (we can add any necessary additional to this PR to make the PR pass tests)
2. bundling all upgrades in 1 PR greatly reduces the noise from all these dependabot PRs.

I think this is a very good start & if necessary, we could split the PRs into more groups.

**Comment by erikgb** [comment]
SGTM! 🚀 🚢

**Comment by maelvls** [comment]
/approve

Thank you @erikgb for reviewing!

**Pull request merged**
