### PR TITLE
Add hostNetwork and scheduling options

### PR DESCRIPTION
**Pull request by rickymulder**
* Added option to expose pod on hostNetwork, set default to false
* Added scheduling options for affinity, nodeSelector, and tolerations
* ran `make generate`
* ran `./hack/update-helm-docs.sh`
* Addresses #147

### CODE REVIEW

**Comment by rickymulder** [comment]
@JoshVanL 
I've closed out the original #148 , rebased, and followed your instructions to sign and update this PR.  I hope this can be merged, if not please inform me of any action items.

**Comment by JoshVanL** [comment]
Thanks!

/approve
/lgtm

**Comment by JoshVanL** [comment]
Whoopa. fat finger

/approve
/lgtm
/ok-to-test

**Comment by rickymulder** [comment]
@JoshVanL 
I do not see any github actions configured for publishing a new chart to the jetstack helm repo, only uploaded to the github releases.  Is there some non-obvious way to have this published to the official helm repo?

**Pull request merged**
