### PR TITLE
Updates controller-runtime to 0.10.0

### PR DESCRIPTION
**Pull request by JoshVanL**
Signed-off-by: joshvanl <vleeuwenjoshua@gmail.com>

/assign @irbekrm

### CODE REVIEW

**Comment by irbekrm** [comment]
Somehow the PR here doesn't get updated properly, need to investigate

It appears running https://prow.build-infra.jetstack.net/log?container=test&id=1435539940233449472&job=pull-cert-manager-approver-policy-smoke

**Comment by JoshVanL** [comment]
@irbekrm Might be to do with the fact that I changed master -> main

**Comment by irbekrm** [comment]
> dial tcp: lookup charts.jetstack.io on 10.8.240.10:53: read udp 10.8.2.4:45959->10.8.240.10:53: i/o timeout

really need to prioritize looking into this

/retest

**Comment by JoshVanL** [comment]
@irbekrm Could be way off, but I am hoping this does something https://github.com/cert-manager/approver-policy/pull/31/commits/bde0903a2c66719651c41c4348207ff7621ddf15

**Comment by irbekrm** [comment]
Should probably do the same in cert-manager

/lgtm
/approve

**Pull request merged**
