### PR TITLE
fix: typos in error message wrapping

### PR DESCRIPTION
**Pull request by erikgb**
Fixes https://github.com/cert-manager/approver-policy/issues/301

/cc @wallrj

### CODE REVIEW

**Review by wallrj — APPROVED** [review]
Thanks!

/approve
/lgtm
/hold in case you also want to fix the `con` variable name. Else unhold and do that in another PR.

**Comment by erikgb** [comment]
> in case you also want to fix the con variable name

Thanks! Good catch. Done.

**Review by wallrj — APPROVED** [review]
/lgtm

**Pull request merged**
