### PR TITLE
Allows to add custom annotation to approver policy pod

### LINKED ISSUE #195: Allow metrics to be scraped through prometheus annotations
Allow prometheus annotations to be used to scrape metrics from cert-manager-approver

```yaml
app:
  metrics:
    # new - unifies path between annotations and service - defaults to pre-existing path
    path: /metrics
    prometheus:
      # new - allows service discovery of metrics endpoint by annotation
      enabled: false
```

### PR DESCRIPTION
**Pull request by bradfordwagner**
Allows to add custom annotations to approver policy pod.

closes #195

### CODE REVIEW

**Comment by bradfordwagner** [comment]
@inteon  - Is there anything else I can do to help move this PR forward?

**Comment by irbekrm** [comment]
Hi @bradfordwagner thanks for the PR!

Could you please add a description as to what change is being added in this PR and how it compares with the existing Helm chart values for enabling a service monitor + why you need it and can't use the existing values?
Also would be good to squash the commits in this PR so it's easier to understand what is actually being changed.

**Comment by bradfordwagner** [comment]
Hello @irbekrm

I wanted to allow custom annotations. Our metrics are gathered using a prometheus scraper on the from the /metrics endpoint using auto discovery (annotations-based). Opening this up to entering custom annotations would additionally allow vault webhook injector, etc annotations to be added if necessary.

**Review by irbekrm — APPROVED** [review]
Thanks for making the changes!

I see that the actual prometheus specific annotations were taken out.

/lgtm
/approve

**Pull request merged**
